### ISSUE TITLE
Unhandled Promise rejection: Quotes are not supported for evaluation!

### ISSUE THREAD

**Issue by brtka** [MurhafSousli/ngx-disqus#1]
Hi there, 
 
I'm trying to add disqus to ionic2 app, i'm testing this on localhost, so I tried to add the [url]="http://mysitename.com", but I got this error message on compile:

`polyfills.js:3 Unhandled Promise rejection: Quotes are not supported for evaluation! ; Zone: <root> ; Task: Promise.then ; Value: Error: Quotes are not supported for evaluation!(…) Error: Quotes are not supported for evaluation!`

any ideas how to fix this, or how to implement your package to ionic2? 

Thx

**Comment by MurhafSousli** [comment]
Hi @Brle88,
I haven't tested it on ionic2, are you sure that this error is caused by this package?
check the [source](https://github.com/MurhafSousli/ng2-disqus/blob/master/src/disqus/disqus.component.ts)
I'm using the global variable `window` which may or may not be supported in ionic2, which starter are you using?

**Comment by AbraamNader** [comment]
Hi @Brle88 
it's working great, I'm on ionic 3.
a bit late but for anyone having the same problem while initially testing using an actual string :)
you just need to have single quotes when binding to a literal string not a variable, so use this instead:
[url]="**'**http://mysitename.com**'**"

when using a variable don't add the single quotes, you use it like so:
[url]="siteUrl"
